### ISSUE TITLE
Populate the Technician Profession

### ISSUE THREAD

**Issue by draksterau** [StargateMC/Server#101]
Needs to have a list of items that are rewarded for the following;

- Break/mine
- Place
- Craft

@messra20 Can you list cables/computers/machines and recommended rewards for the technician please?

**Comment by messra20** [comment]
though i wont be able to do so physically in game for a little while ill start writting up a list referencing everything i remember and will go from there

**Comment by draksterau** [comment]
@messra20 Will look at restoring your base when you're on next.

Krazy bypassed factions somehow.

**Comment by messra20** [comment]
even though im offline off the server i still hear things and am well informed of a tnt cart +active stargate chain reaction detonation of my poor poor pyramid

**Comment by messra20** [comment]
ok for the technician job i think itll be easier if we just go by crafting and just drop the whole place/break/mine thing or if they are required just set those values to 0 because you really dont have to worry about machines being moved alot they stay in place alot of the time unless they get moved for relocation and thats very rare

**Comment by messra20** [comment]
Personal Note for the assigned issue

IC2 Machines made with:
Basic Machine Casings reward less cash and xp
Advanced Machine Casings Reward more cash and xp
Machines that require multiple machines requiring Advanced machine casings reward more cash and xp

Thermal Expansion Machine
can be made with multiple casing types aside from basic

Applied Energistics 2
Machines to be listed later on
